# docker-compose.yml

services:
  web:
    build: .
    container_name: doc_intellect_app
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 --timeout 120 app:app
    volumes:
      - .:/app
      # Mount the drives you want to scan
      - /mnt/d:/scan-targets/d_drive:ro
    ports:
      - "5001:5000"
    # This now correctly points to the official Tika service
    environment:
      TIKA_SERVER_URL: 'http://tika:9998/tika'
    depends_on:
      # This healthcheck ensures Tika is fully running before the web app starts
      tika:
        condition: service_healthy

  # The official Apache Tika Server, ready for production use
  tika:
    image: apache/tika:latest-full
    container_name: tika_server
    ports:
      - "9998:9998"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/tika"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web