# docker-compose.yml (Clean version for VirtualBox)

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doc_intellect_app
    command: gunicorn --bind 0.0.0.0:5000 --workers 2 --timeout 120 app:app # Reduced workers for a VM
    volumes:
      - .:/app
      # --- IMPORTANT: USER ACTION REQUIRED ---
      # Add the path to your document folders INSIDE the VM here.
      # Example: - /home/reza/my_legal_docs:/scan-targets/legal_docs:ro
    ports:
      - "5001:5000"
    environment:
      TIKA_SERVER_URL: 'http://tika:9998/tika'
    depends_on:
      tika:
        condition: service_healthy

  tika:
    build:
      context: .
      dockerfile: tika.Dockerfile
    container_name: tika_server
    ports:
      - "9998:9998"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/tika"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web